import { Box, Container, Grid, Typography } from "@mui/material";
import React from "react";
import ServicesCard from "./ServicesCard";
import {
  Bookmark,
  Extension,
  Language,
  Laptop,
  LocalLibrary,
  QuestionAnswer,
} from "@mui/icons-material";

const serviceCardIcons = [
  <Laptop />,
  <LocalLibrary />,
  <Language />,
  <Extension />,
  <Bookmark />,
  <QuestionAnswer />,
];
const serviceCardHeaders = [
  "Smart Study Room",
  "Interactive Learning",
  "Study in Your Favorite Language",
  "Fun Learning with Games",
  "Follow ups & Academic Advising",
  "Knowledge Transfer Platform",
];
const serviceCardTexts = [
  "You will not leave the room until you finish your study, you can take notes, learning terminology and new words.  More importantly, your class teacher will go with you at the study time in the Smart Study Room",
  "You will enjoy studying and getting fun learning by interacting with your lessons and learning contents in several ways.  Not only fun learning but also deeper understanding with less efforts.",
  "If you feel that the lesson is hard to study in English, you can look at the Arabic translation or use the subtitle in your favorite language.  If your eyes are tired to read, listen to the narration.  Parents can follow and study the lessons in their favorite language (Arabic, English, or French).",
  "Now memorizing the terminology and its definition is made fun.  Games are automatically generated by the system for you to enjoy memorizing the spelling of the words and remember their definitions.",
  "The system will automatically assess your learning achievement and satisfaction of lessons’ goals.  Analytics of your study style will give the teacher and the parent a report on your status quo early enough",
  "End-of-Term Review Platform (LXE) allows you to ask the system a question and it will reply automatically, or you put your question for either the teacher or your colleagues answer.  Teachers can place the exam review questions with answers, or leaving the answers to the students",
];

const Services = () => {
  return (
    <Box className="services">
      <Container>
        <Typography variant="h2" className="section-title" align="center">
          What Services We Provide
        </Typography>
        <Grid container spacing={4} rowSpacing={8}>
          {serviceCardIcons.map((icon, idx) => (
            <Grid key={idx} item xs={4}>
              <ServicesCard
                icon={icon}
                title={serviceCardHeaders[idx]}
                text={serviceCardTexts[idx]}
              />
            </Grid>
          ))}
        </Grid>
      </Container>
    </Box>
  );
};

export default Services;
